# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.92.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods

  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Download/create certificates and profiles"
  lane  :provisioning do
    cert(development: true, output_path: "provisioning")
    cert(output_path: "provisioning")

    sigh(development: true, output_path: "provisioning")
    sigh(adhoc: true, output_path: "provisioning")
    sigh(output_path: "provisioning")
  end

  desc "Download/create push certificates"
  lane :push do
      pem(development: true, output_path: "provisioning/push")
      pem(output_path: "provisioning/push")
  end

  desc "Submit a new Beta Build to Crashylitcs"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    ensure_git_status_clean
    ensure_git_branch(branch: 'master')
    # git_pull
    # push_to_git_remote
    increment_build_number()
    gym(export_method: "ad-hoc", scheme: "SchedulesAdhoc") # Build your app - more options available
    crashlytics(crashlytics_path: "./Crashlytics.framework/")
    # pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Schedules2") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
